### ISSUE TITLE
Just a bit of personal comment :)

### ISSUE THREAD

**Issue by LouisSzeto** [JaskaranBakshi/Lean.DataSource.QuiverCNBC#2]
Hi Jas! Nice to meet you here!

I hope this is not bothering you. Given that I've taken a look at the Quiver CNBC submitted to LEAN, I wish to provide a humble comment on the Universe Selection logic for better utilizing the dataset. This is completely personal opinion though, so I hope you'd found this is not out of criticism or impoliteness.

For myself, I think this way would be more useful for universe file:
`[SID,ticker,bullishViews,neutralViews,bearishViews]`
where they could be the number of analysts holding those view, or a list of analyst name in case people might want to follow a certain analyst; possibly could also abstract into `.Count` & `.Traders` attributes

**bullish:** direction contains `"Buy,Hold,Long,Bullish"`
**bearish:** direction contains `"Sell,Trim,Short,Bearish"`
**neutral:** direction didn't contain the above, i.e. `"Speculative,Final Trade"`
all universe data had to be filled forward if no new view from an existing analyst.

These makes researches easy for particular analyst performance or over score like `# bullish views - # bearish views` by Spearman correlation, sign ranked test or ML.

**Comment by jas10022** [comment]
Hi @LouisSzeto, this definitely seem like an amazing idea to implement for the CNBC dataset as it will make the dataset more actionable in terms of values for people to trade on. I can try to implement this into the code, but given that you have but some thought into this do you have a rough idea as to where the changes will be needed in the repo.

**Comment by JaskaranBakshi** [comment]
Hi [@LouisSzeto](https://github.com/LouisSzeto), this definitely seem like an amazing idea to implement for the CNBC dataset as it will make the dataset more actionable in terms of values for people to trade on. I can try to implement this into the code, but given that you have but some thought into this do you have a rough idea as to where the changes will be needed in the repo.

**Comment by LouisSzeto** [comment]
Hi! I think you may want to store some of [these guys](https://github.com/JaskaranBakshi/Lean.DataSource.QuiverCNBC/blob/adf993ecdb2c0aece434ad4d4473394c1cfe49b6/DataProcessing/QuiverCNBCDataDownloader.cs#L149-L152) in a `Dictionary<ticker, Dictionary<traders, direction>>` for rolling over dates and write into daily universe ConcurrentDictionary `_tempData`. (Should be most of the work)

All attributes in the [universe class](https://github.com/JaskaranBakshi/Lean.DataSource.QuiverCNBC/blob/adf993ecdb2c0aece434ad4d4473394c1cfe49b6/QuiverCNBCUniverse.cs#L40-L53) have to be changed with the [unit test](https://github.com/JaskaranBakshi/Lean.DataSource.QuiverCNBC/blob/adf993ecdb2c0aece434ad4d4473394c1cfe49b6/tests/QuiverCNBCUniverseTests.cs), 
probably a new class `CNBCViewsBase` for abstracting `.Count` and `.Traders` attributes for the 3 types of views with a `Parse` method.

Then the demo algos are piece of cake.

**Comment by JaskaranBakshi** [comment]
Made some changes in the pr above, wanted to make sure I was on the right track

**Comment by LouisSzeto** [comment]
I made a PR to make most of the thing working. I'm assuming everyday has data though, but if it is not the case, we'll need to fetch all trading days for the ConcurrentDictionary __tempData_.

**Comment by JaskaranBakshi** [comment]
I think that assumption is right for this dataset.

**Comment by LouisSzeto** [comment]
I guess it is good to go for review from Alex and Martin :)
